[build]
builder = "NIXPACKS"
buildCommand = "cd frontend && npm install && npm run build && cd ../backend && npm install"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
